- hosts: tag_Name_{{ customer|replace ("-","_") }}_{{ project|replace ("-","_") }}_{{env}}
  gather_facts: no
  remote_user: platon
  become: true
  vars_files:
    - ansible_variable.yml

  pre_tasks:
  - raw: test -e /usr/bin/python || (zypper -n install  python)
  - setup: # aka gather_facts

  tasks:
  - name: Sleeping for 60 seconds
    command: sleep 60

  - name: Creates directory
    file:
      path: /usr/sap
      state: directory

  - name: Create a xfs filesystem on /dev/sdc
    filesystem:
      fstype: xfs
      dev: /dev/sdc

  - mount:
      fstype: xfs
      src: /dev/sdc
      path: /usr/sap
      state: mounted


  - name: Creates directory
    file:
      path: /hana/data
      state: directory

  - name: Create a xfs filesystem on /dev/sdd
    filesystem:
      fstype: xfs
      dev: /dev/sdd

  - mount:
      fstype: xfs
      src: /dev/sdd
      path: /hana/data
      state: mounted


  - name: Creates directory
    file:
      path: /hana/log
      state: directory

  - name: Create a xfs filesystem on /dev/sde
    filesystem:
      fstype: xfs
      dev: /dev/sde

  - mount:
      fstype: xfs
      src: /dev/sde
      path: /hana/log
      state: mounted


  - name: Creates directory
    file:
      path: /hana/shared
      state: directory

  - name: Create a xfs filesystem on /dev/sdf
    filesystem:
      fstype: xfs
      dev: /dev/sdf

  - mount:
      fstype: xfs
      src: /dev/sdf
      path: /hana/shared
      state: mounted

